// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbMkxPv-wkRY0EWUNXPfeOw_ew27O73V8',
    appId: '1:58347477505:web:bdfb7a0780dd3f74c9fe00',
    messagingSenderId: '58347477505',
    projectId: 'walking-buddy-bf642',
    authDomain: 'walking-buddy-bf642.firebaseapp.com',
    storageBucket: 'walking-buddy-bf642.firebasestorage.app',
    measurementId: 'G-9HQY8YD1Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA29MsGWMhR413UPKbSsDxzQ_4Mhxwtde0',
    appId: '1:58347477505:android:bdc0d24cbbef1bc8c9fe00',
    messagingSenderId: '58347477505',
    projectId: 'walking-buddy-bf642',
    storageBucket: 'walking-buddy-bf642.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgWBdhJ-RcHERtPmDgBY_4pTM1eMMJND4',
    appId: '1:58347477505:ios:c8e8e1161c0213e6c9fe00',
    messagingSenderId: '58347477505',
    projectId: 'walking-buddy-bf642',
    storageBucket: 'walking-buddy-bf642.firebasestorage.app',
    iosBundleId: 'com.example.walkinbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgWBdhJ-RcHERtPmDgBY_4pTM1eMMJND4',
    appId: '1:58347477505:ios:c8e8e1161c0213e6c9fe00',
    messagingSenderId: '58347477505',
    projectId: 'walking-buddy-bf642',
    storageBucket: 'walking-buddy-bf642.firebasestorage.app',
    iosBundleId: 'com.example.walkinbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbMkxPv-wkRY0EWUNXPfeOw_ew27O73V8',
    appId: '1:58347477505:web:b917d132c541476bc9fe00',
    messagingSenderId: '58347477505',
    projectId: 'walking-buddy-bf642',
    authDomain: 'walking-buddy-bf642.firebaseapp.com',
    storageBucket: 'walking-buddy-bf642.firebasestorage.app',
    measurementId: 'G-1HT7656MRD',
  );
}
